### ISSUE TITLE
I don't like the way we do config

### ISSUE THREAD

**Issue by zleyyij** [r-Techsupport/hyde#217]
It's ewy, some variables are read on startup, some variables are read every time they're needed, it's unclear what variables are required and what variables aren't

**Comment by Xeckt** [comment]
Few ways to tackle this - as agreed in Discord to go forward using a `toml` config for the future.

One way is to use a static global, but if it's a global it's not exactly "good" as we store secrets in the config.

The other way to do it is to store a `Config` struct into `AppState` struct, and then add apply it to the defined app in main. The only take from this is every function that requires data from the config will need to have an `AppState` parameter, which can end up generating some overhead. 

In my opinion, especially at this stage it's good to focus importance on memory usage. We would already have to clone `Config` data to the `BasicAuth` client for oauth, albeit it's small amounts of data, there isn't a way (at least that I can see) to simplify this, but I probably need to think about this more. 

```rust
async fn init_state() -> Result<AppState> {
    let config = Arc::new(Config::load("./default.toml"));
    let git = task::spawn(async { git::Interface::new() }).await??;
    let reqwest_client = Client::new();
    
    // We have to clone here 
    let oauth = BasicClient::new(
        ClientId::new(config.oauth.discord.client_id.clone()),
        Some(ClientSecret::new(config.oauth.discord.secret.clone())),
        AuthUrl::new(config.oauth.discord.url.clone())?,
        Some(TokenUrl::new(config.oauth.discord.token_url.clone())?),
    );
    
    Ok(AppState {
        config,
        git,
        oauth,
        reqwest_client,
        gh_credentials: GithubAccessToken::new(),
        db: Database::new().await?,
    })
}
```
Maybe there is a way to simplify this approach more but I'm not sure how, any insight on that?

**Comment by zleyyij** [comment]
If the config is wrapped with an Arc, wouldn't memory usage not really be a huge issue?

I don't like the idea of a global static very much simply because it encourages business logic to directly access the config struct.

Honestly I'm fine to throw it in AppState under an arc or whatever, and have handlers read the relevant config values before calling business logic with those config values.

I'm not awake yet, I have no clue if this provided any value to you

**Comment by Xeckt** [comment]
I was thinking to use Arc as well, thought this might be the way forward. My main premise is making sure we are agreed to pass AppState as a param to handler functions whenever required.

**Comment by zleyyij** [comment]
Yeah, that seems to be the best way to do things
